### ISSUE TITLE
Figuring out a Save/Load function

### ISSUE THREAD

**Issue by mlabita37** [mlabita37/BeatConnection#3]
I would like to implement a way to save/load the sequences created on my sequencer. I will only be logging the location and value of each cell and storing them in the DB. Just need help wrapping my head around the best way to approach it so I don't waste time heading in the wrong direction. Not sure if I should be using arrays or objects to store the values. Just wanna run through what my idea is with someone first.

**Comment by Avizacherman** [comment]
C'mon back.

**Comment by mlabita37** [comment]
Hey Avi, I've gone ahead and created my models to store Users and save the Beats for my app. Created my routes and CRUD functions as well. At this point I just need a little help implementing my save/load functions. I'm also having some trouble with my modal for login/signup, it keeps opening on page load regardless of being hidden. Thank you in advance!
